import { useEffect, useState } from "react";
import { getNeighborhood } from "../api";
import type { NeighborhoodDetail } from "../types/city";
import "./NeighborhoodMonitoring.css";
const number = new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 });
const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
function Gauge({ label, value, danger=false }: { label:string; value:number; danger?:boolean }) { return <div className="neighborhood-gauge"><span>{label}<b>{number.format(value)} %</b></span><i><em className={danger?"danger":""} style={{width:`${Math.max(0,Math.min(100,value))}%`}} /></i></div>; }
export function NeighborhoodModal({ neighborhoodId, paused, snapshotTick, onClose, onSelectBuilding, onSelectIncident, onSelectVehicle }: { neighborhoodId:number|null; paused:boolean; snapshotTick:number; onClose:()=>void; onSelectBuilding:(id:number)=>void; onSelectIncident:(id:number)=>void; onSelectVehicle:(id:number)=>void }) {
 const [data,setData]=useState<NeighborhoodDetail|null>(null); const [loading,setLoading]=useState(false); const [refreshing,setRefreshing]=useState(false);
 useEffect(()=>{ if(neighborhoodId===null){setData(null);return;} let disposed=false,inFlight=false; const initial=data?.id!==neighborhoodId; if(initial)setData(null); const refresh=async(first:boolean)=>{if(inFlight)return;inFlight=true;first?setLoading(true):setRefreshing(true);try{const next=await getNeighborhood(neighborhoodId);if(!disposed)setData(next);}finally{inFlight=false;if(!disposed){setLoading(false);setRefreshing(false);}}};void refresh(initial);const timer=paused?null:window.setInterval(()=>void refresh(false),1500);return()=>{disposed=true;if(timer!==null)window.clearInterval(timer);};},[neighborhoodId,paused,paused?snapshotTick:0]);
 if(neighborhoodId===null)return null;
 return <div className="citizen-modal-overlay" role="dialog" aria-modal="true" aria-label="Fiche quartier" onMouseDown={onClose}><section className="citizen-modal neighborhood-modal" onMouseDown={(event)=>event.stopPropagation()}><header className="citizen-modal-header"><div><div className="eyebrow">Quartier · #{neighborhoodId}</div><h2>{data?.name??"Chargement…"}</h2><p>{data?`${data.population} habitants · attractivité ${number.format(data.attractiveness)} %`:"Récupération des données"}</p></div><div className="citizen-modal-actions">{data&&<span className={`live-status${refreshing?" refreshing":""}${paused?" paused":""}`}><i />{paused?"En pause":"En direct"}</span>}<button onClick={onClose}>Fermer</button></div></header>
 <div className="citizen-modal-body">{loading&&!data?<div className="profile-loading">Chargement du quartier…</div>:!data?<div className="profile-loading">Quartier introuvable.</div>:<div className="neighborhood-grid">
  <section className="profile-section"><h3>Profil territorial</h3><dl className="profile-facts"><div><dt>Revenu moyen</dt><dd>{euro.format(data.averageIncome)}</dd></div><div><dt>Chômage</dt><dd>{number.format(data.unemploymentRate)} %</dd></div><div><dt>Loyer moyen</dt><dd>{euro.format(data.averageRent)}</dd></div><div><dt>Temps de transport</dt><dd>{number.format(data.averageTransportMinutes)} min</dd></div><div><dt>Réponse policière</dt><dd>{number.format(data.averageResponseMinutes)} min</dd></div><div><dt>Éclairage</dt><dd>{number.format(data.lighting)} %</dd></div></dl><Gauge label="Sécurité ressentie" value={data.safetyPerception}/><Gauge label="Attractivité" value={data.attractiveness}/><Gauge label="Pression des services" value={data.servicePressure} danger/></section>
  <section className="profile-section"><h3>Accès et activité</h3><Gauge label="Couverture policière" value={data.policeCoverage}/><Gauge label="Accès aux soins" value={data.healthcareAccess}/><Gauge label="Accès aux commerces" value={data.commerceAccess}/><Gauge label="Criminalité" value={data.criminality} danger/><dl className="profile-facts"><div><dt>Activité commerciale</dt><dd>{number.format(data.commercialActivity)}</dd></div><div><dt>Entreprises</dt><dd>{data.businesses.length}</dd></div><div><dt>Services</dt><dd>{data.services.length}</dd></div><div><dt>Patrouilles</dt><dd>{data.patrols.length}</dd></div></dl><div className="neighborhood-links">{data.patrols.map((row)=><button key={row.id} onClick={()=>onSelectVehicle(row.id)}>Unité #{row.id} · {row.status}</button>)}</div></section>
  <section className="profile-section profile-section-wide"><h3>Entreprises et services</h3><div className="neighborhood-entities">{[...data.businesses,...data.services].map((row)=><button key={`${row.type}-${row.id}`} onClick={()=>onSelectBuilding(row.id)}><span><strong>{row.name}</strong><small>{row.type.replace(/_/g," ")}</small></span><b>Service {number.format(row.serviceLevel)} %</b></button>)}</div></section>
  <section className="profile-section"><h3>Incidents récents</h3><div className="neighborhood-incidents">{data.incidents.length===0?<p className="muted">Aucun incident enregistré.</p>:data.incidents.slice(0,12).map((row)=><button key={row.id} onClick={()=>onSelectIncident(row.id)}><span><strong>{row.title}</strong><small>{row.status}</small></span><b>{row.severity}</b></button>)}</div></section>
  <section className="profile-section"><h3>Tendances journalières</h3>{data.history.length===0?<p className="muted">Les premières tendances seront disponibles à la fin de la journée.</p>:<div className="neighborhood-history">{data.history.slice(-14).reverse().map((row)=><article key={row.day}><b>J{row.day}</b><span>Sécurité {number.format(row.safetyPerception)} %</span><span>Crime {number.format(row.criminality)}</span><span>Attractivité {number.format(row.attractiveness)} %</span></article>)}</div>}</section>
 </div>}</div></section></div>;
}
